### PR TITLE
Audio Message Feature: Player, Recorder, Sending & Display

### PR DESCRIPTION
**Pull request by MathJud**
This PR is the followup of PR #615 
For Testing before merging.

### CODE REVIEW

**Comment by MathJud** [comment]
### Linux: Flutter Error when Playing a Audio Message

Try to play received audio message
The Audio message was playing and flutter crashed.

- I could hear the audio message, it looked normal
- during the playback flutter crashed
- the path exists, the file exists
  - maybe it needs to be named `file:///` (this would be a correct URI)

Error Log

```
flutter: [SEVERE] 	(2024-05-05 16:20:25.932356): ProcessException: No such file or directory
flutter:   Command: fmedia --globcmd.pipe-name=record_linux/dc4708a7-1328-433b-86a8-008f84481085 --globcmd=stop
flutter: [INFO] LogStorageManager	(2024-05-05 16:20:26.020745): storing log "qaul_log-ProcessException-1714918825978.gzip" in directory:
flutter: 	/home/sojus/.local/share/net.qaul.qaul/ui_logs
[FATAL:flutter/fml/thread_local.cc(32)] Check failed: false. pthread_setspecific failed (22): Invalid argument
```

----

Second Error Log

```
flutter: AudioPlayers Exception: AudioPlayerException(
	DeviceFileSource(path: /home/sojus/.config/qaul/12D3KooWMN1FkdNJbPMHZ4Y2DUAJxaHzqeRwZdXatP4Vdc1ejGd5/files/17108486664303233428.m4a), 
	PlatformException(LinuxAudioError, Unknown GstGError. See details., Invalid URI "/home/sojus/.config/qaul/12D3KooWMN1FkdNJbPMHZ4Y2DUAJxaHzqeRwZdXatP4Vdc1ejGd5/files/17108486664303233428.m4a". (Domain: gst-resource-error-quark, Code: 3), null)
flutter: [SEVERE] 	(2024-05-05 16:43:57.522802): PlatformException(LinuxAudioError, Unknown GstGError. See details., Invalid URI "/home/sojus/.config/qaul/12D3KooWMN1FkdNJbPMHZ4Y2DUAJxaHzqeRwZdXatP4Vdc1ejGd5/files/17108486664303233428.m4a". (Domain: gst-resource-error-quark, Code: 3), null)
flutter: [SEVERE] 	(2024-05-05 16:43:57.524386): PlatformException(LinuxAudioError, Unknown GstGError. See details., Invalid URI "/home/sojus/.config/qaul/12D3KooWMN1FkdNJbPMHZ4Y2DUAJxaHzqeRwZdXatP4Vdc1ejGd5/files/17108486664303233428.m4a". (Domain: gst-resource-error-quark, Code: 3), null)
flutter: [SEVERE] 	(2024-05-05 16:43:57.524549): PlatformException(LinuxAudioError, Unknown GstGError. See details., Invalid URI "/home/sojus/.config/qaul/12D3KooWMN1FkdNJbPMHZ4Y2DUAJxaHzqeRwZdXatP4Vdc1ejGd5/files/17108486664303233428.m4a". (Domain: gst-resource-error-quark, Code: 3), null)
flutter: [INFO] LogStorageManager	(2024-05-05 16:43:57.558824): storing log "qaul_log-PlatformException-1714920237534.gzip" in directory:
flutter: 	/home/sojus/.local/share/net.qaul.qaul/ui_logs
flutter: [INFO] LogStorageManager	(2024-05-05 16:43:57.564013): storing log "qaul_log-PlatformException-1714920237560.gzip" in directory:
flutter: 	/home/sojus/.local/share/net.qaul.qaul/ui_logs
flutter: [INFO] LogStorageManager	(2024-05-05 16:43:57.566418): storing log "qaul_log-PlatformException-1714920237564.gzip" in directory:
flutter: 	/home/sojus/.local/share/net.qaul.qaul/ui_logs
 INFO  libqaul::router::connections   > expired entry=20299,  hc=1
```

**Comment by MathJud** [comment]
### Linux: Flutter Error: When recording Audio Message

Record Audio

- clicking on microphone icon
- recorder modal window opens
- clock begins to count
- when I press stop:
  - The clock stops, nothing else happens ...
  - no error is issued ...
- when I close the modal dialog via the `X` button:
  - the modal window closes
  - a severe flutter error is issued:

```
flutter: [INFO] neat_periodic_task	(2024-05-05 17:16:35.722527): ### [ALIVE] neat-periodic-task: "delete-obsolete-logs"
flutter: [INFO] neat_periodic_task	(2024-05-05 17:16:35.737095): ### [ALIVE] neat-periodic-task: "delete-surpassing-size-logs"
flutter: [SEVERE] 	(2024-05-05 17:16:47.012440): ProcessException: No such file or directory
flutter:   Command: fmedia --globcmd.pipe-name=record_linux/f78d6423-2f3c-4a06-b2dc-31a3c2d9db43 --globcmd=stop
flutter: [INFO] LogStorageManager	(2024-05-05 17:16:47.094391): storing log "qaul_log-ProcessException-1714922207054.gzip" in directory:
flutter: 	/home/sojus/.local/share/net.qaul.qaul/ui_logs
```

**Comment by MathJud** [comment]
### Windows: Flutter Error: When loading the Application

When testing the application, the application window crashes and remains white.
Visual Studio shows an Error related to the plugin `audioplayers_windows_plugin.dll`
The related error is shown in the screenshot below.

Screenshot from 2024-05-06 12-27-49

**Comment by sukhman-sukh** [comment]
Regarding the Windows flutter issue:
Hey @MathJud,
It is still working fine for me.
One issue I sometimes face is that the code editor/ide is unable to identify DLLs (libqaul.dll in my case). It works when I use ```flutter run -d windows ``` and then open the binary file manually at location ```qaul_ui\build\windows\x64\runner\Debug```.
Can you please try testing this way once?
Thanks

**Comment by MathJud** [comment]
work continued in #615

**Pull request closed without merging**
