### PR TITLE
New Android Background Execution Mode

### PR DESCRIPTION
**Pull request by MathJud**
To keep qaul app running in the background, qaul used a flutter plugin.
This PR implements an own alternative implementation to have better control and reach all the qualities intended.

### CODE REVIEW

**Comment by MathJud** [comment]
On Android 11 it is working fine.
On Android 12, the app crashes with the following error:

```
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(10460): FATAL EXCEPTION: main
E/AndroidRuntime(10460): Process: net.qaul.qaul_app, PID: 10460
E/AndroidRuntime(10460): java.lang.RuntimeException: Unable to create service net.qaul.qaul_app.FlutterBackgroundService: java.lang.IllegalArgumentException: net.qaul.qaul_app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(10460): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(10460): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4668)
E/AndroidRuntime(10460): 	at android.app.ActivityThread.access$100(ActivityThread.java:254)
E/AndroidRuntime(10460): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2203)
E/AndroidRuntime(10460): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10460): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(10460): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(10460): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(10460): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10460): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(10460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(10460): Caused by: java.lang.IllegalArgumentException: net.qaul.qaul_app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(10460): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(10460): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:378)
E/AndroidRuntime(10460): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:461)
E/AndroidRuntime(10460): 	at android.app.PendingIntent.getActivity(PendingIntent.java:447)
E/AndroidRuntime(10460): 	at android.app.PendingIntent.getActivity(PendingIntent.java:411)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.FlutterBackgroundService.createNotification(FlutterBackgroundService.kt:113)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.FlutterBackgroundService.startService(FlutterBackgroundService.kt:85)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.FlutterBackgroundService.access$startService(FlutterBackgroundService.kt:22)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.FlutterBackgroundService$checkAndRequestPermissions$1.invoke(FlutterBackgroundService.kt:74)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.FlutterBackgroundService$checkAndRequestPermissions$1.invoke(FlutterBackgroundService.kt:72)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.PermissionHandler.checkAndRequestPermissions(PermissionHandler.kt:33)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.FlutterBackgroundService.checkAndRequestPermissions(FlutterBackgroundService.kt:72)
E/AndroidRuntime(10460): 	at net.qaul.qaul_app.FlutterBackgroundService.onCreate(FlutterBackgroundService.kt:52)
E/AndroidRuntime(10460): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4655)
E/AndroidRuntime(10460): 	... 9 more
Error connecting to the service protocol: failed to connect to http://127.0.0.1:42173/8JonWueeUhc=/

```

**Comment by MathJud** [comment]
On my Android 11 device it is working fine and background & program execution is stopped fine after hitting the exit button. 

I made the following discoveries:

- When exiting it via the exit button a few times in a row, I received an Android warning, that the app keeps stopping and whether I wanted to close the app. This behaviour is IMHO OK.
- When swiping the window away from the previewed windows, the app successfully closed, as I would have expected. As it is hidden from the open-app-window/recents overview, I couldn't test if this is also happening when swiping the window away there. Maybe we don't even need this exit button anymore?

I have the following suggestions:

- show the window of the app in the open-app-window/recents overview, when the app is running in the background. When this view is hidden, the user has longer to get back to the app, and It appears, as if the app had crashed or somehow disappeared.
- when tapping the permanent notification, the app should come to front.
- Regarding user information: I suggest to make an information link in the settings where we can activate/deactivate the background execution. (once we have this)

**Comment by brenodt** [comment]
@MathJud I addressed all the points you've suggested, thanks for the feedback!

Care to review once more and let me know what you think?

Things to check:
- app reinstated to appear on "Recents" android view
- once closed, background execution is automatically terminated
- exit button has been removed for now
- tapping on the persistent notification resumes the app
- fixed the error you were having on Android 12
- added option to manually enable/disable app from the settings screen
- added "?" button that routes to a screen that will contain an explanation for the Android background execution

#### TODO
if you could help me creating the content for the explanation screen, I'd appreciate it a lot!
The explanation should be written in markdown (the file with the placeholder is at `qaul_ui/assets/about/android_background_execution.md`).

**Comment by MathJud** [comment]
@brenodt  great work!

I'm going to merge this one, in order to better test the BLE feature.

**Pull request merged**
